apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookstore
  name: bookstore
  namespace: application
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - bookstore
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: sami4rhimi/go-webapp:v4
        imagePullPolicy: IfNotPresent
        name: go-webapp
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"