apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: application
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 2
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.0.17
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: nfs-pvc
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: nfs-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
